/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chataja.view;

import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * Creates new form myUtama
     */
    public frm_utama() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnChat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnFriend = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnHome = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnSetting = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlChat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlFriend = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnCari = new javax.swing.JLabel();
        txtFriend = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        pnlSetting = new javax.swing.JPanel();
        btnAbot = new javax.swing.JLabel();
        btnLogut = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenu.setLayout(new java.awt.CardLayout());

        jToolBar1.setRollover(true);

        btnChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chataja/assets/icons8-speech-bubble-64.png"))); // NOI18N
        btnChat.setText("Chat");
        btnChat.setFocusable(false);
        btnChat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChat);
        jToolBar1.add(jSeparator1);

        btnFriend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chataja/assets/icons8-contacts-64.png"))); // NOI18N
        btnFriend.setText("Friend");
        btnFriend.setFocusable(false);
        btnFriend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFriend.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriendActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFriend);
        jToolBar1.add(jSeparator2);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chataja/assets/icons8-home-64.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHome);
        jToolBar1.add(jSeparator3);

        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chataja/assets/icons8-tune-64.png"))); // NOI18N
        btnSetting.setText("Setting");
        btnSetting.setFocusable(false);
        btnSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSetting);

        pnlMenu.add(jToolBar1, "card2");

        getContentPane().add(pnlMenu, java.awt.BorderLayout.PAGE_END);

        pnlUtama.setLayout(new java.awt.CardLayout());

        pnlChat.setBackground(new java.awt.Color(30, 139, 195));

        jScrollPane1.setBackground(new java.awt.Color(30, 139, 195));

        jTable1.setBackground(new java.awt.Color(30, 139, 195));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pengirim", "Pesan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout pnlChatLayout = new javax.swing.GroupLayout(pnlChat);
        pnlChat.setLayout(pnlChatLayout);
        pnlChatLayout.setHorizontalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlChatLayout.setVerticalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlUtama.add(pnlChat, "card2");

        pnlFriend.setBackground(new java.awt.Color(107, 185, 240));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel1.setText("Contact List");

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chataja/assets/icons8-handshake-40.png"))); // NOI18N
        btnCari.setText("Add Friend");

        txtFriend.setToolTipText("Cari Pertemanan");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout pnlFriendLayout = new javax.swing.GroupLayout(pnlFriend);
        pnlFriend.setLayout(pnlFriendLayout);
        pnlFriendLayout.setHorizontalGroup(
            pnlFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFriendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFriendLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlFriendLayout.createSequentialGroup()
                        .addGroup(pnlFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6)
                            .addComponent(txtFriend, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnCari)
                        .addGap(29, 29, 29))
                    .addGroup(pnlFriendLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlFriendLayout.setVerticalGroup(
            pnlFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFriendLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFriendLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFriendLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnlFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCari)
                            .addComponent(txtFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlFriend, "card3");

        pnlHome.setBackground(new java.awt.Color(103, 128, 159));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        pnlUtama.add(pnlHome, "card4");

        pnlSetting.setBackground(new java.awt.Color(228, 241, 254));

        btnAbot.setText("About");

        btnLogut.setText("Logout");
        btnLogut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSettingLayout = new javax.swing.GroupLayout(pnlSetting);
        pnlSetting.setLayout(pnlSettingLayout);
        pnlSettingLayout.setHorizontalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogut, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlSettingLayout.setVerticalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnAbot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlSetting, "card5");

        getContentPane().add(pnlUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        // TODO add your handling code here:
        pnlUtama.removeAll();
        pnlUtama.repaint();
        pnlUtama.revalidate();
        
        pnlUtama.add(pnlChat);
        pnlUtama.repaint();
        pnlUtama.revalidate();
    }//GEN-LAST:event_btnChatActionPerformed

    private void btnFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriendActionPerformed
        // TODO add your handling code here:
        pnlUtama.removeAll();
        pnlUtama.repaint();
        pnlUtama.revalidate();
        
        pnlUtama.add(pnlFriend);
        pnlUtama.repaint();
        pnlUtama.revalidate();
    }//GEN-LAST:event_btnFriendActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        pnlUtama.removeAll();
        pnlUtama.repaint();
        pnlUtama.revalidate();
        
        pnlUtama.add(pnlHome);
        pnlUtama.repaint();
        pnlUtama.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        pnlUtama.removeAll();
        pnlUtama.repaint();
        pnlUtama.revalidate();
        
        pnlUtama.add(pnlSetting);
        pnlUtama.repaint();
        pnlUtama.revalidate();
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLogutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        frm_login login = new frm_login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbot;
    private javax.swing.JLabel btnCari;
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnFriend;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel btnLogut;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlChat;
    private javax.swing.JPanel pnlFriend;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTextField txtFriend;
    // End of variables declaration//GEN-END:variables
}
